name: FUTBIN Scraper

on:
  # Ejecuta una vez al día a las 3 PM UTC (9 AM hora local aproximadamente)
  schedule:
    - cron: '0 15 * * *'
  # También se puede ejecutar manualmente
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    steps:
    - name: Checkout código
      uses: actions/checkout@v4
    
    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Instalar dependencias del sistema
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          wget \
          gnupg \
          ca-certificates \
          fonts-liberation \
          libasound2 \
          libatk-bridge2.0-0 \
          libatk1.0-0 \
          libatspi2.0-0 \
          libcups2 \
          libdbus-1-3 \
          libdrm2 \
          libgbm1 \
          libgtk-3-0 \
          libnspr4 \
          libnss3 \
          libx11-6 \
          libx11-xcb1 \
          libxcb1 \
          libxcomposite1 \
          libxdamage1 \
          libxext6 \
          libxfixes3 \
          libxkbcommon0 \
          libxrandr2 \
          libxshm1 \
          libxss1 \
          libxtst6 \
          xdg-utils
    
    - name: Instalar dependencias Python
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Verificar Chrome instalado
      run: |
        which google-chrome || echo "Chrome no encontrado en PATH"
        google-chrome --version || echo "No se puede obtener versión de Chrome"
    
    - name: Ejecutar scraper
      id: scraper
      env:
        CI: 'true'
      run: |
        python run_scraper.py
    
    - name: Notificar resultados del scraper
      env:
        NTFY_TOPIC: ${{ secrets.NTFY_TOPIC }}
      if: success() || failure()
      run: |
        python send_scraper_notification.py || true
      continue-on-error: true
    

