name: FUTBIN Scraper

on:
  # Ejecuta una vez al día a las 3 PM UTC (9 AM hora local aproximadamente)
  schedule:
    - cron: '0 15 * * *'
  # También se puede ejecutar manualmente
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-22.04
    timeout-minutes: 15
    
    steps:
    - name: Checkout código
      uses: actions/checkout@v5
    
    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Instalar dependencias del sistema
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libnss3 \
          libatk1.0-0 \
          libatk-bridge2.0-0 \
          libcups2 \
          libdrm2 \
          libdbus-1-3 \
          libxkbcommon0 \
          libxcomposite1 \
          libxdamage1 \
          libxfixes3 \
          libxrandr2 \
          libgbm1 \
          libasound2 \
          libpango-1.0-0 \
          libcairo2 \
          libatspi2.0-0 \
          libxss1 \
          libasound2-dev
    
    - name: Instalar dependencias Python
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Instalar navegadores de Playwright
      run: python -m playwright install chromium
    
    - name: Ejecutar scraper
      id: scraper
      env:
        CI: 'true'
      run: |
        python run_scraper.py
    
    - name: Notificar resultados del scraper por ntfy
      env:
        NTFY_TOPIC: ${{ secrets.NTFY_TOPIC }}
      if: always()
      run: |
        python send_scraper_notification.py || true
      continue-on-error: true