name: FUTBIN Scraper

on:
  # Ejecuta una vez al día a las 3 PM UTC (9 AM hora local aproximadamente)
  schedule:
    - cron: '0 15 * * *'
  # También se puede ejecutar manualmente
  workflow_dispatch:

jobs:
  scraper:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-node@v5
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    
    steps:
    - name: Checkout código
      uses: actions/checkout@v5
    
    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Instalar dependencias Python
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Ejecutar scraper
      id: scraper
      env:
        CI: 'true'
      run: |
        python run_scraper.py
    
    - name: Notificar resultados del scraper por ntfy
      env:
        NTFY_TOPIC: ${{ secrets.NTFY_TOPIC }}
      if: always()
      run: |
        python send_scraper_notification.py || true
      continue-on-error: true